---
#- name: Install ca-certificates
#  apt: name=ca-certificates state=present
#
#- name: Add Jenkins repository key
#  apt_key: id=D50582E6 url=https://pkg.jenkins.io/debian/jenkins.io.key
#
#- name: Add Jenkins repository
#  apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' state=present update_cache=yes
#
# Restart with a task instead of a handler, since we need those changes to
# be applied right away so that we can use the admin password in API calls.
#- name: Restart Jenkins if necessary
#  service: name=jenkins state=restarted
#  when: jenkins_defaults is changed or jenkins_admin_config is changed

- name: Install jenkins
  include_tasks: install.yml
  when: install_jenkins == True

- name: Configure jenkins
  include_tasks: configure.yml
  when: install_jenkins == False
